version: '3.9'

services:
  chore-tracker:
    container_name: chore-tracker
    image: chore-tracker-v1
    restart: always
    working_dir: /app
    platform: 'linux/amd64'
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_CLIENTVAR: 'clientvar'
    ports:
      - '3001:3000'
    environment:
      - DATABASE_URL=your_db_url_here
